### ISSUE TITLE
[BUG] LiteDB Docs FileStorage section "fs.Find("$/photos/2014/");" not supported in v5

### ISSUE THREAD

**Issue by lanwah** [litedb-org/LiteDB#2506]
**Version**
LiteDB version 5.0.20.0

**Describe the bug**
LiteDb Docs FileStroage section.

// Find all files references in a "directory"
var files = fs.Find("$/photos/2014/");

Not supported writing in v5.
It is recommended to add different versions of writing instructions for the Find method

**Expected behavior**
Supported writing for the Find method in different versions.
we can write like this in v5:

fs.Find("_id LIKE @0", path + "%")

or

fs.Find("_id = @0", path);

or

fs.Find("filename = @0", filename)

**Screenshots/Stacktrace**
![image](https://github.com/mbdavid/LiteDB/assets/17949808/71b8d665-ffd7-4538-8243-91247cc2225a)

**Comment by Joy-less** [comment]
After some digging around, this is how you can do it:
```cs
// Open database connection
using LiteDatabase dataBase = new("demo.db");

// Get the file metadata/chunks storage
ILiteStorage<string> fileStorage = dataBase.GetStorage<string>("myFiles", "myChunks");

// Upload empty test file to file storage
using MemoryStream emptyStream = new();
fileStorage.Upload("$/photos/2014/picture-01.jpg", "picture-01.jpg", emptyStream);

// Find photos from 2014
var files = fileStorage.Find("_id LIKE '$/photos/2014/%'"); // returns 1 LiteFileInfo
```

The `LIKE` statement uses the [SQL syntax](https://www.w3schools.com/SQL/sql_like.asp) where `%` is the wildcard character.

If you would like to use parameters, you can use this:
```cs
// Use parameters to avoid SQL injection
var files = fileStorage.Find("_id LIKE @0", "$/photos/2014/%");
```

If you would like to concisely find by the full ID, you can use this:
```cs
// Find by exact ID
var file = fileStorage.FindById("$/photos/2014/picture-01.jpg");
```

This should be updated in the docs; I can confirm what's written there is incorrect.
