### ISSUE TITLE
[SUGGESTION] .NET 8.0 for MAUI support

### ISSUE THREAD

**Issue by weslleymurdock** [litedb-org/LiteDB#2560]
**FEATURE:**
Add .NET 8.0 support to use in .NET MAUI applications

**SOLUTION**
The solution to use this library in .NET MAUI apps is add a target framework for net8.0 in order to be available for use in .NET MAUI apps.

**Alternatives**
I've not found any other way to use the lib on .NET 8 using MAUI stack.

**Comment by DDZ-DO** [comment]
Am I missing something? 
It supports .Net Standard 2.0 which is supported by .Net 8. 
I'm using it in a .Net 8 asp.net project without a problem.

**Comment by Joy-less** [comment]
.NET 8.0 should support .NET Standard 1.3/2.0.
However, we are looking into supporting .NET 8.0.
